version: '3.7'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      - my-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  my-network:
    external: true
