version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - my-network
    volumes:
      - redis-data:/data
    restart: unless-stopped

networks:
  my-network:
    external: true

volumes:
  redis-data:
